### ISSUE TITLE
Get initial package(s) filenames from loader.Program

### ISSUE THREAD

**Issue by thomasheller** [mvdan/lint#10]
Assuming a linter implements `Checker` as follows, but needs the original filenames because it doesn't actually operate on the AST, but rather does raw text operations like checking line-length, spelling etc. Does it really need to get the filenames via `token.Position`?

```go
func Checker(lprog *loader.Program, prog *ssa.Program) {
       for _, info := range lprog.InitialPackages() {
                for _, file := range info.Files {
                        pkg := file.Package
                        pos := lprog.Fset.Position(pkg)
                        fmt.Println(pos.Filename) // do something with files
                }
        }
}
```

Am I missing something obvious?

**Comment by bradleyfalzon** [comment]
> Does it really need to get the filenames via token.Position?

What exactly do you mean by this? Does it really need so much boilerplate just to get the filename? Or is as simple as just using the fileset to obtain the filename?

**Comment by thomasheller** [comment]
The boilerplate. I somehow thought an `ast.File` knows about its name, but it looks like it doesn't.

**Comment by bradleyfalzon** [comment]
Yeah it would be convenient, but having said that, maybe it's a convenience function lint could provide `func ASTFilePath(lprog *loader.Program, file *ast.File) (path string)` or something like `func InitialFiles(lprog *loader.Program) (paths []string)`

**Comment by thomasheller** [comment]
It actually makes sense that `ast.File` doesn't know about the actual file, so there's an abstraction from the underlying file system. However, I find the `ast.File.Name` field is a bit misnamed - it contains the package name, although you would expect to get the filename. But let's not get side-tracked.

So if we go with the three linter levels @mvdan suggested in #9, then level 0 linters either:
- Each need to run the above code to get the filenames (iterate packages and files, query `Position`)
- metalint passes the filenames through the `Checker` interface (if requested, at least)
- lint provides a convenience function like `InitialFiles` (as suggested above)

**Comment by mvdan** [comment]
The more I think about it, the more I realise we always want to use `go/loader`. It handles special import paths for us for example, like `std`, `cmd/foo` or `all`. And for linters that don't need ASTs, it's just some extra unnecessary work - all they need is still there.

I agree that, for linters that need filenames of the Go files, having to do that boilerplate is a bit repetitive. Adding a helper func like `InitialFiles` sounds fine to me.

**Comment by mvdan** [comment]
Let's hold this off until `go/loader` gets overhauled in a few months. If such a helper func is still useful in the new API, and it won't get included in `go/loader` itself, we can add it here instead.

**Comment by mvdan** [comment]
Still no news from the `go/loader` overhaul, unfortunately. Hopefully something will happen soon :)

**Comment by mvdan** [comment]
Now that `go/packages` and `go/analysis` are a thing, this repo lost its purpose.
