### ISSUE TITLE
Extra information in the Issue struct

### ISSUE THREAD

**Issue by mvdan** [mvdan/lint#2]
I assume `token.Pos` is enough to point at a certain problem. With the caller's `token.FileSet`, that's enough to get filename, line and column. I don't think we need end positions for linters.

I wonder if a message string is enough on its own, though. Some linters categorize their warnings. Some others might want to give hints on what the developer should do. Should all of these just be part of the string, or should they be treated separately?

**Comment by mvdan** [comment]
Aside from keeping just the two fields or adding more specific fields like a category or a hint, we can also add a "metadata" field of type `map[string]interface{}` or even `interface{}`. Then each linter would say what it fills it with.

On one hand this could be terribly overkill. On the other, it's only one field and it will be very easy to extend while keeping backwards compatibility. And we don't have to dictate what are the possible attributes that issues can have.

This could also be used to filter what issues are reported.

**Comment by mvdan** [comment]
Currently leaning towards `interface{}` as then it could be filled with a struct type that gives a nicer usage and better type safety than `map[string]interface{}`.

Or, you could still put a `map[string]interface{}` there if you wish.

**Comment by mvdan** [comment]
It just dawned on me - why on earth is this a struct and not an interface? We can simply do:

```go
type Issue interface {
    Pos() token.Pos
    Message() string
}
```

Particular implementations can add extra public fields or methods if they wish. And the interface can be extended without breaking backwards compat. This is also much nicer than fitting a "metadata" struct in an `interface{}` field.

**Comment by mvdan** [comment]
@bradleyfalzon @thomasheller what do you think of the interface above? IMO it's a big improvement over the current struct, and it will be easily extensible without breaking backwards compat.

Perhaps the only disadvantage is that it will often require pointers, thus allocations. But since linters are usually very heavy and the number of issues should be small-ish, I don't think that's a factor at all.

**Comment by bradleyfalzon** [comment]
Yeah I agree on the interface, being able to type switch would make it much easier to extract the additional information if required. As for performance, I'd continue using an interface until it's a problem. So yes, agree on both accounts.

**Comment by mvdan** [comment]
Awesome, thank you both for the input.
