### ISSUE TITLE
Avoid work with linters that don't need ssa

### ISSUE THREAD

**Issue by mvdan** [mvdan/lint#5]
If a linter doesn't need ssa it's a bit silly to load all of that if no other linters need it.

Right now, the interface doesn't let linters specify what information they need.

For simplicity, let's not include type info here. `go/loader` has type info at its core, and I don't believe any linter is particularly useful only with `go/ast`.

**Comment by mvdan** [comment]
A way to do this could be to split up `Check` into multiple methods, e.g.:

```go
type Checker interface {
    Program(*loader.Program)
    UsesSSA() bool
    WithSSA(*ssa.Program)
    Check() ([]Issue, error)
}
```

Then ssa would only be loaded and passed via `WithSSA` if `UsesSSA` returned true.

**Comment by mvdan** [comment]
Actually, even better:

```go
type Checker interface {
    Program(*loader.Program)
    Check() ([]Issue, error)
}

type WithSSA interface {
    ProgramSSA(*ssa.Program)
}
```

Then linters could implement `WithSSA` if they require ssa to work.

**Comment by mvdan** [comment]
The more I think about it, the more I convince myself that SSA should not be a core/required part of the interface.

Not only is it unnecessary in most linters, but the actual `golang.org/x/tools/go/ssa` package is, and I quote, `EXPERIMENTAL AND IS LIKELY TO CHANGE`.

I'll think about the actual names a bit more and post a PR asking for feedback.

**Comment by mvdan** [comment]
Oh, as it turns out `go/loader` has the same experimental API notice. But this one is much older and much more widely used among linters, so having it as a base is acceptable.

**Comment by thomasheller** [comment]
Out of curiosity, I came up with a Go script that analyzes existing linters' input requirements (see [golinters](https://github.com/thomasheller/golinters) for the results). Many linters don't use `go/loader`, but of those that do, few use `go/ssa`. Linters operating on plain text are pretty rare. So, just to confirm: It makes sense to split things up and avoid SSA work when possible.

**Comment by mvdan** [comment]
That's amazing - thanks!

By the way, I exchanged some emails with Alan and I have a much better picture of the future of go/loader now - things will be better for our interface. I'll open an issue with details once I'm back from holiday.

**Comment by mvdan** [comment]
#11 now in place - if none of the linters require SSA, `cmd/metalint` will not build the `ssa.Program` at all.
