### ISSUE TITLE
Use an union of TypeCheckFuncBodies

### ISSUE THREAD

**Issue by mvdan** [mvdan/lint#8]
Right now linter implementations cannot define what func bodies they need type-checked. So at the moment, `metacheck` and any other tools have to be safe and type-check everything.

This works fine, but especially on packages with lots of dependencies this can lead to lots of wasted time.

I propose that each linter may expose a `TypeCheckFuncBodies` method. If they don't, it defaults to `return true` - type-check all func bodies, like we do now. We must be safe if we don't know better.

Either way, when running multiple linters we can use the union of all of these funcs as follows (simplified):

```
fn := func(path string) bool {
    for _, c := range checkers {
        if c.TypeCheckFuncBodies(path) {
            return true
        }
    }
    return false
}
```

This way, if none of the linters we're running need to type-check the func bodies of a package, we won't. As soon as one of them does (or hasn't implemented the method), we will.

**Comment by mvdan** [comment]
Would also be great if linters could say "I only need type-checking of the packages given as arguments", i.e. `lprog.InitialPackages()`. But this isn't currently possible, as far as I know: https://github.com/golang/go/issues/18288

**Comment by mvdan** [comment]
@bradleyfalzon @thomasheller thoughts on this one? Out of all the current ideas in the issue tracker, it's the only one that I have zero doubts about.

**Comment by bradleyfalzon** [comment]
I'm on the fence, it seems straight forward to implement in `lint` or in the client library, but as soon as one package sets it to true, everyone pays the penalty. So it may not be worth implementing, and keeping this API simpler until we know the number of linters that require it - but it's not really complicating things either.

I guess I wouldn't implement this until I knew there is going to be a benefit, and that depends on which tools adopt these interfaces.

**Comment by mvdan** [comment]
It's true that, in practice, tools like `metalint` will just end up type-checking all bodies. At the same time, using that as a reason not to make this configurable seems like limiting the power that the checkers have to precisely define what they need and don't need done.

You're right that keeping the API simpler might be a good idea for now, though. It won't break backwards compatibility to add it later. Leaving the issue open for now.

**Comment by mvdan** [comment]
Let's re-evaluate this once the `go/loader` API gets overhauled in the next few months. There might not even be a `TypeCheckFuncBodies` anymore, then.
